agent:
  clientId: "${WIZ_OUTPOST_CLIENT_ID}"
  clientSecret: "${WIZ_OUTPOST_CLIENT_SECRET}"
  outpostId: "${WIZ_OUTPOST_ID}"
imagePullSecrets:
- name: wiz-outpost-lite-image-pull
replicaCount: 2
runners:
  rem-custom-0004:
    enabled: true
  rem-custom-0005:
    enabled: true
  rem-custom-0006:
    enabled: true
  rem-custom-0007:
    enabled: true
